
# # version: '3.7'

# # services:
# #   postgres:
# #     image: postgres:9.6
# #     environment:
# #       - POSTGRES_USER=airflow
# #       - POSTGRES_PASSWORD=airflow
# #       - POSTGRES_DB=airflow
# #     ports:
# #       - "5432:5432"  # Expose PostgreSQL to host
# #     volumes:
# #       - postgres-db-volume:/var/lib/postgresql/data
# #     logging:
# #       options:
# #         max-size: 10m
# #         max-file: "3"

# #   webserver:
# #     image: puckel/docker-airflow:1.10.9
# #     restart: always
# #     depends_on:
# #       - postgres
# #     environment:
# #       - LOAD_EX=n
# #       - EXECUTOR=Local
# #       - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@host.docker.internal:5432/airflow
# #       # Optional: configure SMTP if needed later
# #       # - AIRFLOW__SMTP__SMTP_HOST=smtp.gmail.com
# #       # - AIRFLOW__SMTP__SMTP_USER=your_email@gmail.com
# #       # - AIRFLOW__SMTP__SMTP_PASSWORD=your_password
# #     logging:
# #       options:
# #         max-size: 10m
# #         max-file: "3"
# #     volumes:
# #       - ./dags:/usr/local/airflow/dags
# #       # - ./plugins:/usr/local/airflow/plugins
# #     ports:
# #       - "36027:8080"
# #     command: webserver
# #     healthcheck:
# #       test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
# #       interval: 30s
# #       timeout: 30s
# #       retries: 3

# # volumes:
# #   postgres-db-volume:

#  DOCker COMPOSE YAML FILE ------------------------------------------------------------------------------------------------------------------------


version: '3.7'

services:
  postgres:
    image: postgres:9.6
    container_name: airflow_postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    logging:
      options:
        max-size: 10m
        max-file: "3"

  webserver:
    image: puckel/docker-airflow:1.10.9
    container_name: airflow_webserver
    restart: always
    depends_on:
      - postgres
    environment:
      LOAD_EX: 'n'
      EXECUTOR: Local
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - ./dags:/usr/local/airflow/dags
      - ./data:/usr/local/airflow/data
    ports:
      - "36027:8080"
    command: webserver
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3

volumes:
  postgres-db-volume:
